# Generated by Django 5.2.8 on 2025-11-29 14:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo / Razão Social')),
                ('tipo_pessoa', models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], default='FISICA', max_length=10)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço Completo')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(max_length=50, unique=True, verbose_name='Número do Protocolo')),
                ('hash_acesso_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('ATO_NOTARIAL', 'Ato Notarial'), ('CERTIDAO', 'Certidão')], default='ATO_NOTARIAL', max_length=20)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('ESCRITURA_FINALIZADA', 'Escritura Finalizada'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=25)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_agendamento', models.DateField(blank=True, null=True, verbose_name='Data Agendamento')),
                ('horario_agendamento', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('deposito_previo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Depósito Prévio')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('observacoes_ato_notarial', models.TextField(blank=True, null=True, verbose_name='Obs. Específica Ato Notarial')),
                ('lista_documentos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Lista de Documentos Entregues')),
                ('advogados', models.ManyToManyField(blank=True, related_name='protocolos_como_advogado', to='core.cliente', verbose_name='Advogados')),
                ('clientes', models.ManyToManyField(related_name='protocolos_como_cliente', to='core.cliente', verbose_name='Clientes Envolvidos')),
            ],
        ),
        migrations.CreateModel(
            name='Tabelionato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacao', models.CharField(max_length=255, verbose_name='Denominação')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Configuração do Tabelionato',
                'verbose_name_plural': 'Configuração do Tabelionato',
            },
        ),
        migrations.CreateModel(
            name='TipoAto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Ato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tempo_alerta', models.DurationField(blank=True, help_text='Tempo padrão para alerta (ex: DD HH:MM:SS)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('MASTER', 'Master'), ('ADMINISTRATIVO', 'Administrativo'), ('ESCREVENTE', 'Escrevente')], default='ESCREVENTE', max_length=20, verbose_name='Função')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DadosEscritura',
            fields=[
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dados_escritura', serialize=False, to='core.protocolo')),
                ('livro', models.CharField(max_length=20, verbose_name='Livro')),
                ('folha', models.CharField(max_length=20, verbose_name='Folha')),
                ('data_escritura', models.DateField(verbose_name='Data da Escritura')),
                ('comunicacao_coaf', models.BooleanField(default=False, verbose_name='Comunicação COAF?')),
                ('relatorio_coaf', models.TextField(blank=True, null=True, verbose_name='Relatório COAF')),
                ('data_comunicacao_coaf', models.DateField(blank=True, null=True)),
                ('numero_comunicacao_coaf', models.CharField(blank=True, max_length=50, null=True)),
                ('documentos_digitalizados', models.BooleanField(default=False, verbose_name='Docs. Digitalizados')),
                ('emolumentos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Emolumentos')),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='protocolo',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComentarioInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastro_municipal', models.CharField(max_length=50, verbose_name='Cadastro Municipal / IPTU')),
                ('valor_venal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Venal')),
                ('valor_negocio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Negócio')),
                ('descricao', models.TextField(verbose_name='Descrição do Imóvel')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to='core.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='JustificativaCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_cancelamento', models.DateTimeField(auto_now_add=True)),
                ('cancelado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificativa_cancelamento', to='core.protocolo')),
            ],
        ),
        migrations.AddField(
            model_name='protocolo',
            name='tipo_ato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoato', verbose_name='Tipo de Ato'),
        ),
    ]
